### PR TITLE
Fixed docker instruction, bash runs fetching, demo runs

### PR DESCRIPTION
**Pull request by Kaszanas**
@geopavlakos The previous instructions run fine.

I am in the process of verifying if the entirety of my solution works with the example data.
To download the example data.

This PR fixes:

```bash
fetch_demo_data.sh
```
ang changes it to (when attached with an interactive terminal to the Docker container):

```bash
bash fetch_demo_data.sh
```

### CODE REVIEW

**Comment by Kaszanas** [comment]
@geopavlakos I am still working on some improvements, I am converting this PR into a draft until I am able to execute the demo script from inside Docker container.

**Comment by Kaszanas** [comment]
Okay at this point this Docker image builds and given proper placement of the models/data in the `_DATA` directory it runs.
There are some improvements over #76 

It is also worth to say that this also applies some of the ideas from #76

**Comment by geopavlakos** [comment]
Just to confirm, is the current version working as is, or are there more updates that we should do?

**Comment by Kaszanas** [comment]
@geopavlakos the current version is working, these are build improvements that should speed up dependency installation.

Originally the COPY was done before each of the dependencies was installed. This means that if any change was done to the files, the cache would be invalidated (at least I think so).

So I did some Docker instruction rearranging (this PR was a draft prior to the fixes made in another PR).

**Comment by geopavlakos** [comment]
I see, sounds good. Please let me know if we need to merge something. Currently, the branch have some conflicts that don't allow merging.

**Comment by Kaszanas** [comment]
@geopavlakos I have fixed the conflicts. As stated in the previous PR on the topic of docker, this one changes the order of operations so that caching can be used more effectively.

Also this is using CUDA 12 version of the NVIDIA image instead of CUDA 11 (but it is backwards compatible from what I know).

I think this can be merged, if you have some time look at the diff and decide ;)

**Pull request merged**
